Unikka:
  FilePreviews:
    apiKey: 'sQjSRy8WGaWo6d5dCDcGQ8Su1OxFY3'
    apiSecret: 'f6VtvhwxhIX3HxBINlM9yxLQZ1rzHi'
    maximumWaitingTime: 30
    retryInterval: 1
    defaultOptions:
      format: 'jpg'

# Configure new thumbnail generator
Neos:
  Media:
    thumbnailGenerators:
      'Unikka\FilePreviews\Domain\Model\ThumbnailGenerator\FilePreviewsThumbnailGenerator':
        maximumFileSize: 2000000
        supportedExtensions: [ 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlxs', 'odt', 'ott', 'odp', 'txt', 'rtf', 'eps', 'psd', 'ai' ]

# Configure job queue for the file preview api async handling
Flowpack:
  JobQueue:
    Common:
      queues:
        'filepreview-queue':
          className: 'Flowpack\JobQueue\Doctrine\Queue\DoctrineQueue'
          maximumNumberOfReleases: 10
          executeIsolated: true
          options:
            defaultTimeout: 50
          releaseOptions:
            priority: 512
            delay: 120
