TYPO3:
  Media:
    thumbnailGenerator:

      'Ttree\FilePreviews\Domain\Model\ThumbnailGenerator\FilePreviewsThumbnailGenerator':
        apiKey: 'api-key'
        apiSecret: 'api-secret'
        maximumWaitingTime: 30
        maximumFileSize: 2000000
        defaultOptions:
          format: 'jpg'
        retryInterval: 1
        supportedExtensions: [ 'doc', 'docx', 'txt', 'rtf', 'ogg' ]
