TYPO3:
  Media:
    thumbnailGenerator:

      'Ttree\FilePreviews\Domain\Model\ThumbnailGenerator\FilePreviewsThumbnailGenerator':
        apiKey: 'api-key'
        apiSecret: 'api-secret'
        maximumWaitingTime: 30
        retryInterval: 1
        supportedExtensions: [ 'doc', 'docx' ]
